{% set version = "8.2" %}

package:
  name: humanfriendly
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/humanfriendly/humanfriendly-{{ version }}.tar.gz
  sha256: bf52ec91244819c780341a3438d5d7b09f431d3f113a475147ac9b7b167a3d12

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - humanfriendly = humanfriendly.cli:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyreadline  # [win]
    - monotonic  # [py2k]

test:
  imports:
    - humanfriendly
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://humanfriendly.readthedocs.org
  license: MIT
  license_file: LICENSE.txt
  summary: Human friendly output for text interfaces using Python.

extra:
  recipe-maintainers:
    - ocefpaf
    - ccordoba12
