{% set version = "10.0" %}

package:
  name: humanfriendly
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/humanfriendly/humanfriendly-{{ version }}.tar.gz
  sha256: 6b0b831ce8f15f7300721aa49829fc4e83921a9a301cc7f606be6686a2288ddc

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - humanfriendly = humanfriendly.cli:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyreadline  # [win and py<38]
    - pyreadline3  # [win and py>=38]

test:
  imports:
    - humanfriendly
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://humanfriendly.readthedocs.org
  license: MIT
  license_file: LICENSE.txt
  summary: Human friendly output for text interfaces using Python.

extra:
  recipe-maintainers:
    - ocefpaf
    - ccordoba12
