{% set version = "4.14" %}

package:
  name: humanfriendly
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/humanfriendly/humanfriendly-{{ version }}.tar.gz
  sha256: 00593bb4ed08b0c0d88b653e4425266c2c14ed22cc03ac196783559d442ca324

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - humanfriendly = humanfriendly.cli:main

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - humanfriendly

about:
  home: https://humanfriendly.readthedocs.org
  license: MIT
  summary: 'Human friendly output for text interfaces using Python.'

extra:
  recipe-maintainers:
    - ocefpaf
