travis:
  secure:
    BINSTAR_TOKEN: CdHI5X1xzAuLoRT3RpynNH+DT2ZgmE47YguiJVD0U7lvHhbFcSr4PAQdehANmEcCUrZZoUJyWTPVdmyyB4Csw9sznw5xQrwYMtMewJzUNNeb+4Kw1NwxVJqTNtL8TiVQWxvnpL218/0vXv4VwRJw1m3Zp7Hk1p/j9PfH1gatzo+vjYtW4u+wP0zxpj3nRdlydCU/ejgMlllg8xMB8iHVM+zxmLxKcA/IE+Bewk68BoWgvm5uQ8dQWAlam9KVzVALbFpINuTUjBHIYFNSifoei+OlgdGQ8Xfze+rrs+2WH6OdvOehsWoV4CRIwTxnjDJVAr3PF6N9DBGhJkKAkw2xCKrBmmxJUPeLtLFlybidGYf5bOjJ0vHZUiHbzOHbFyH8xZ9TPMFdGQx6hDwqURJUBL4daRG3WNgkWH5TYW8pcol+jdpKL0qIuWCkYwFKSXpbtRdz1cJimlbU081MoZHSUSgdl7oZLa7niDkrdmQLNkwh1WPNOHnUKNi1XUhwF2LMb8Y7Pa/aG3zEPepQtYRekl9BE/sJ4s+CHdnRpcGAHX/wUDtyx3an1tPpY1LwT8lxsuwdT1wi1UqvlBkuEp3J+YPByppL5n5Mz0GgrE0DFv+2jjcCyW2Fsy7c1Sn9THsVNQsUlgVF7e4IFG1Ziemmu65NeQ52he6FL7BfaUkhIEc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
