appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: Gqr1fgL4vmHnV/pb3LPvoymZrXizuhZHO+k6pq1qLSYWu4MIM0mxLZpMEzbf3GpYu/5m5Tjy765QWI6DJNlELee8xcJzl+OaVrH4qrqAaTj2HlkUmTDNF4meDg5v85QgRhIIJS6crCizSY1AO6sxldKDPsmLcXhxzJrERb8awvng+8bRCMT8ts3LKWMpa0/Muu0786wQgtnvGb4ZwtXnZcJaIEVYTuZJ7cFgT5Qxouqe77lZsApY3jxs+T4zYbQEGkqMHsiGqCdouA+8pQJD0Bda5LIOvWsZiEUauvlBQ5eIGnrlOl/Cv7pIKGqbW+E9n22s1afmv3JTbLmFNIsXyOrBR0WS6VK13yhQ3lVtmD/zaSvuI3+lToDtU7kJE59F8mlv6gpcpCgn1PEV8fmzz0FSSOC0j2B/yDX3UUt26a8iXbSWw3rtUuWVBtOL2UHUdWVuE4rBAyM7rmIC0J0Jk7LX6tcZM20eifDJkwerpgXnHQoiIp0pjQidQoBbiE5XeYjxgL0NWEHUvvtWkaDGyilLR2kj+oL8T0lmDN2+U7gihc4qzwP9u7uXCHtv3NJOl6T1VAa93iJSh9NS+ltBSGT+hkyMR0zHOZN6YTDRKhfvQTu94dvhslqlsz6p46U8y6/+jjIEeRjy97gW0DvA2RFFvFcNJXethWZuHsGozBo=}
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: true
